### ISSUE TITLE
DAIDE - ENG Translation

### ISSUE THREAD

**Issue by DenisPeskov** [ALLAN-DIP/diplomacy_cicero#24]
PRP (ALY (RUS TUR FRA) VSS (ENG))
must become easily readable for a human (some variation of "I, France, propose an alliance with you, Turkey, and Russia against England"

**Comment by SiddarGu** [comment]
Fixed by https://github.com/SiddarGu/daidepp/commit/364cccc01a640392bf2c4269a08831e28b9bbcf1
